#' Generate default parameter control settings
#'
#' Creates a list of control parameters for generating random or constant values
#' used in other functions, such as `set_alpha`, `set_beta`, or `set_r`. This
#' function provides default values and allows users to override them as needed.
#'
#' @param type Character. The type of parameter generation. Options are:
#'   \describe{
#'     \item{constant}{Use a fixed value.}
#'     \item{exp}{Draw values from an exponential distribution.}
#'     \item{unif}{Draw values from a uniform distribution.}
#'     \item{normal}{Draw values from a normal distribution.}
#'   }
#' @param mu Numeric. Mean or fixed value used for `constant`, `exp`, and `normal` types. Default is 1.
#' @param sd Numeric. Standard deviation for the `normal` type. Default is 0.1.
#' @param min Numeric. Minimum value for the `unif` type. Default is 0.
#' @param max Numeric. Maximum value for the `unif` type. Default is 1.
#'
#' @return A list containing the control settings: `type`, `mu`, `sd`, `min`, and `max`.
#' @export

par.control <- function(type = c("constant", "exp", "unif", "normal"),
                        mu = 1,
                        sd = 0.1,
                        min = 0,
                        max = 1) {

  type <- match.arg(type)

  list(
    type = type,
    mu   = mu,
    sd   = sd,
    min  = min,
    max  = max
  )
}

#' Generate Diagonal and Interaction Coefficients
#'
#' Creates an \eqn{s \times s} coefficient matrix whose diagonal elements
#' represent self-regulation terms and whose off-diagonal elements represent
#' interaction strengths. The distribution and parameters used to generate these
#' coefficients are controlled via `alpha.control` and `beta.control`, which are
#' lists produced by [par.control()].
#'
#' The diagonal elements are generated from `alpha.control`, while the full
#' matrix (before overwriting the diagonal) is generated from `beta.control`.
#' Each control list specifies the type of distribution (`"constant"`, `"exp"`,
#' `"unif"`, or `"normal"`) and its associated parameters.
#'
#' @param s Integer. The dimension of the coefficient matrix.
#' @param alpha.control A list generated by [par.control()] that specifies how
#'   to generate the \eqn{s} diagonal coefficients. User-supplied values override
#'   defaults through partial matching via [modifyList()].
#' @param beta.control A list generated by [par.control()] that specifies how
#'   to generate the \eqn{s \times s} matrix of off-diagonal coefficients.
#'   User-supplied values override defaults through [modifyList()].
#' @param negative Logical. If `TRUE` (default), all coefficients are multiplied
#'   by `-1`, making them negative. If `FALSE`, coefficients remain positive.
#'
#' @details
#' For `type = "constant"`, `mu` may be either a scalar or a vector of length
#' \eqn{s} for `alpha.control`, and either a scalar or an \eqn{s \times s}
#' matrix for `beta.control`. For all other types, random draws are generated
#' from the appropriate distribution.
#'
#' The diagonal of the resulting matrix is always replaced by the values
#' generated from `alpha.control`, ensuring that diagonal and off-diagonal
#' coefficients can be specified independently. The `negative` argument allows
#' the user to control the sign of the coefficients.
#'
#' @return
#' A numeric \eqn{s \times s} matrix of coefficients.
#'
#' @examples
#' # Default: negative constant self-effects and interaction effects
#' set_coef(s = 4)
#'
#' # Uniform variation in diagonal coefficients
#' set_coef(s = 4, alpha.control = list(type = "unif", min = 0.5, max = 2))
#'
#' # Normal variation in off-diagonal interaction strengths
#' set_coef(s = 4, beta.control = list(type = "normal", mu = 0, sd = 0.2))
#'
#' # Keep coefficients positive
#' set_coef(s = 4, negative = FALSE)
#'
#' @export

set_coef <- function(s,
                     alpha.control = par.control(),
                     beta.control = par.control(),
                     negative = TRUE) {

  # Merge user values with defaults
  if (!is.list(alpha.control))
    stop("'alpha.control' must be a list.")
  if (!is.list(beta.control))
    stop("'beta.control' must be a list.")

  alpha.control <- modifyList(par.control(), alpha.control)
  beta.control <- modifyList(par.control(), beta.control)

  v_alpha <- with(alpha.control, {
    switch(type,

           constant = {
             if (length(mu) == 1) {
               rep(mu, times = s)
             } else {
               if (length(mu) != s)
                 stop("'mu' in 'alpha.control' must be scalar or vector of length ", s)

               mu
             }
           },

           exp = {
             if (mu <= 0) stop("'mu' must be positive for 'exp' type")

             rexp(n = s,
                  rate = 1 / mu)
           },

           unif = runif(n = s,
                        min = min,
                        max = max),

           normal = rnorm(n = s,
                          mean = mu,
                          sd = sd),

           stop("Unsupported type in 'alpha.control'.")
    )
  })

  m_coef <- with(beta.control, {
    switch(type,

           constant = {
             if (length(mu) == 1) {
               matrix(mu,
                      nrow = s,
                      ncol = s)
             } else {
               if (!is.matrix(mu) || any(dim(mu) != c(s, s)))
                 stop("'mu' in 'beta.control' must be scalar or s x s matrix when type = 'constant'.")

               mu
             }
           },

           exp = {
             if (mu <= 0) stop("'mu' must be positive for 'exp' type")

             matrix(rexp(n = s * s,
                         rate = 1 / mu),
                    nrow = s,
                    ncol = s)
           },

           unif = matrix(runif(n = s * s,
                               min = min,
                               max = max),
                         nrow = s,
                         ncol = s),

           normal = matrix(rnorm(n = s * s,
                                 mean = mu,
                                 sd = sd),
                           nrow = s,
                           ncol = s),

           stop("Unsupported type in 'beta.control'.")
    )
  })

  diag(m_coef) <- v_alpha

  m_coef <- negative * (-m_coef) + (1 - negative) * m_coef

  return(m_coef)
}

#' Generate Species Growth Rates
#'
#' Generates a numeric vector of intrinsic growth rates (\eqn{r}) for a set of
#' species. The length of the vector is specified by `s`, and the distribution
#' and parameters used to generate these rates are controlled via `r.control`,
#' which is a list produced by [par.control()].
#'
#' @param s Integer. The number of species, i.e., the length of the resulting
#'   growth rate vector.
#' @param r.control A list generated by [par.control()] that specifies how to
#'   generate the vector of growth rates. User-supplied values override defaults
#'   through partial matching via [modifyList()].
#'
#' @details
#' The `r.control` list specifies the type of distribution (`"constant"`,
#' `"exp"`, `"unif"`, or `"normal"`) and its associated parameters (`mu`, `sd`,
#' `min`, `max`). For `type = "constant"`, `mu` may be a scalar or a vector of
#' length \eqn{s}. For other types, random draws are generated from the specified
#' distribution. For `exp` type, `mu` must be positive.
#'
#' @return
#' A numeric vector of length \eqn{s} containing the growth rates.
#'
#' @examples
#' # Default: constant growth rates
#' set_r(s = 5)
#'
#' # Exponentially distributed growth rates
#' set_r(s = 5, r.control = list(type = "exp", mu = 0.5))
#'
#' # Uniformly distributed growth rates
#' set_r(s = 5, r.control = list(type = "unif", min = 0, max = 1))
#'
#' # Normally distributed growth rates
#' set_r(s = 5, r.control = list(type = "normal", mu = 0.5, sd = 0.1))
#'
#' @export

set_r <- function(s,
                  r.control = par.control()) {

  # Ensure r.control is a list
  if (!is.list(r.control))
    stop("'r.control' must be a list.")

  # Merge user-supplied control with defaults
  r.control <- modifyList(par.control(), r.control)

  # Generate vector of r values
  v_r <- with(r.control, {
    switch(type,
           constant = {
             if (length(mu) == 1) {
               rep(mu, times = s)
             } else {
               if (length(mu) != s)
                 stop("'mu' in 'r.control' must be scalar or vector of length ", s)
               mu
             }
           },

           exp = {
             if (mu <= 0) stop("'mu' must be positive for 'exp' type")
             rexp(n = s, rate = 1 / mu)
           },

           unif = runif(n = s,
                        min = min,
                        max = max),

           normal = rnorm(n = s,
                          mean = mu,
                          sd = sd),

           stop("Unsupported type in 'r.control'.")
    )
  })

  return(v_r)
}

#' Population Dynamics Function
#'
#' This function returns an update function corresponding to a chosen
#' population dynamics model. The returned function takes current abundances and
#' model parameters to compute the next time-step abundances, with an option for
#' demographic stochasticity. The function currently supports two models:
#' \itemize{
#'   \item \code{"bh"}: Beverton–Holt model with density dependence.
#'   \item \code{"ricker"}: Ricker model with density dependence.
#' }
#'
#' Both models incorporate a vector of environmental stochastic effects
#' (\code{eps}) and a density-dependence matrix (\code{m_coef}).
#' When \code{stochastic = TRUE}, abundances are drawn
#' from a Poisson distribution; otherwise, expected values are returned.
#'
#' @param model A character string specifying the model to use. Supported values
#'   are \code{"bh"} for Beverton–Holt and \code{"ricker"} for the Ricker model.
#'
#' @return A function that computes one time-step update of population
#' abundances. The returned function has arguments:
#' \code{r}, \code{n}, \code{m_coef}, \code{eps}, and \code{stochastic}.
#'
#' @export

fn_model <- function(model) {

  dyn <- switch(model,
                bh = function(r,
                              n,
                              m_coef,
                              eps,
                              stochastic = FALSE) {

                  n_bar <- (n * exp(r)) / (1 + m_coef %*% n)
                  n_hat <- n_bar * exp(eps)

                  if (stochastic) {
                    y <- rpois(n = length(n_hat),
                               lambda = n_hat)
                  } else {
                    y <- drop(n_hat)
                  }

                  return(y)
                },

                ricker = function(r,
                                  n,
                                  m_coef,
                                  eps,
                                  stochastic = FALSE) {

                  n_bar <- n * exp(r + m_coef %*% n)
                  n_hat <- n_bar * exp(eps)

                  if (stochastic) {
                    y <- rpois(n = length(n_hat),
                               lambda = n_hat)
                  } else {
                    y <- drop(n_hat)
                  }

                  return(y)
                },

                stop("Unsupported model type")
  )

  return(dyn)
}


#' Simulate community dynamics with stock enhancement
#' @export

csim <- function(ts = 1000,
                 warmup = 100,
                 burnin = 100,
                 s = 10,
                 r.control = par.control(),
                 alpha.control = par.control(),
                 beta.control = par.control(),
                 model = c("ricker", "bh"),
                 negative = NULL,
                 sd_eps = 0.1,
                 stochastic = FALSE,
                 seed = 5,
                 seed_interval = 10,
                 extinct = 0) {

  # model type --------------------------------------------------------------

  model <- match.arg(model)
  if (is.null(negative))
    negative <- ifelse(model == "ricker", TRUE, FALSE)

  dyn <- fn_model(model = model)

  # variables ---------------------------------------------------------------
  ## basic objects ####
  n_sim <- warmup + burnin + ts
  n_cut <- warmup + burnin
  cnm <- c("ts",
           "species",
           "density")

  m_dyn <- matrix(NA,
                  nrow = ts * s,
                  ncol = length(cnm))

  colnames(m_dyn) <- cnm

  st_row <- seq(from = 1,
                to = nrow(m_dyn),
                by = s)

  v_n <- rep(seed, s)

  ## parameter: species interaction ####
  m_coef <- set_coef(s = s,
                     alpha.control = alpha.control,
                     beta.control = beta.control,
                     negative = negative)

  ## parameter: population dynamics ####
  v_r <- set_r(s = s,
               r.control = r.control)

  ## parameter: environmental stochasticity ####
  m_eps <- matrix(rnorm(n = n_sim * s,
                        mean = 0,
                        sd = sd_eps),
                  nrow = n_sim,
                  ncol = s,
                  byrow = TRUE) # time x species matrix

  ## seed interval ####
  if (warmup > 0) {

    if (seed_interval > warmup)
      stop("warmup must be equal to or larger than seed_interval")

    seeding <- seq(from = seed_interval,
                   to = max(c(1, warmup)),
                   by = seed_interval)

  }

  # dynamics ----------------------------------------------------------------

  ## initialize m_dyn[,]
  m_dyn[1:s, ] <- cbind(rep(1, s), # time step
                        seq_len(s), # species ID
                        v_n # density
  )

  for (i in 2:n_sim) {

    # seeding
    if (warmup > 0) {

      if (i %in% seeding) {

        v_n <- v_n + rpois(s, seed)

      }

    }

    v_n <- dyn(r = v_r,
               n = v_n,
               m_coef = m_coef,
               eps = m_eps[i, ],
               stochastic = stochastic)

    v_n[v_n < extinct] <- 0

    if (i > n_cut) {

      row_id <- seq(from = st_row[i - n_cut],
                    to = st_row[i - n_cut] + (s - 1),
                    by = 1)

      m_dyn[row_id, ] <- cbind(rep(i, s) - n_cut, # timestep
                               seq_len(s), # species ID
                               v_n # density
      )
    }
  }

  # return ------------------------------------------------------------------

  df_dyn <- dplyr::as_tibble(m_dyn)

  return(df_dyn)

}
